### ISSUE TITLE
Output folder Not being Created

### ISSUE THREAD

**Issue by Chilly100** [skyte/relative-strength#1]
Hi,
I was hoping you could help me, I've tried running your application but I just get a black command window then a few lines get created and then it closes.  Unfortunately I can't see the lines because it closes to quickly.  There is no output folder created so I suspect it's and access issue but is there any way of seeing the text that gets created in the command window before it closes.

Thanks

**Comment by skyte** [comment]
> is there any way of seeing the text that gets created in the command window before it closes

Run the exe file from the command line like this https://www.wikihow.com/Run-an-EXE-File-From-Command-Prompt .

**Comment by Chilly100** [comment]
Thanks for your help
