### ISSUE TITLE
Would you like to be added to OPENBB ?(Open Source finance platform)

### ISSUE THREAD

**Issue by hairygodfather** [skyte/relative-strength#3]
@skyte 

Hi,
I recently made a suggestion that your ratings would be a valuable addition to the Open Source finance platform, OPENBB (formely Gamestonk terminal). 

Are you interested? 

If yes, I'm sure they would like to connect with you to discuss further. 
You can reach OPEN BB via https://twitter.com/openbb_finance or https://discord.com/invite/xPHTuHCmuV .

**Comment by skyte** [comment]
Hm missed this post until now.
If you want you can copy / fork any of my repositories and use the stuff however you like, but I'm actually not using it anymore and I probably won't do any more work on it.
